### ISSUE TITLE
Niche payment handler error

### ISSUE THREAD

**Issue by brianlenz** [NarrativeNetwork/tokensale-neo-smartcontract#9]
```
Could not process notify event: object of type 'ContractParameter' has no len()
  File "neo/contrib/narrative/nrve-niche-payment-handler.py", line 300, in <module>
    main()
  File "neo/contrib/narrative/nrve-niche-payment-handler.py", line 296, in main
    event_handler.run()
  File "/app/neo-python/neo/contrib/narrative/blockchain/main.py", line 74, in run
    reactor.run()
  File "/app/neo-python/venv/lib/python3.6/site-packages/twisted/internet/base.py", line 1261, in run
    self.mainLoop()
  File "/app/neo-python/venv/lib/python3.6/site-packages/twisted/internet/base.py", line 1270, in mainLoop
    self.runUntilCurrent()
  File "/app/neo-python/venv/lib/python3.6/site-packages/twisted/internet/base.py", line 896, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/app/neo-python/venv/lib/python3.6/site-packages/twisted/internet/task.py", line 239, in __call__
    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
  File "/app/neo-python/venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/app/neo-python/neo/Implementations/Blockchains/LevelDB/LevelDBBlockchain.py", line 850, in PersistBlocks
    self.Persist(block)
  File "/app/neo-python/neo/Implementations/Blockchains/LevelDB/LevelDBBlockchain.py", line 828, in Persist
    events.emit(event.event_type, event)
  File "/app/neo-python/venv/lib/python3.6/site-packages/pymitter/__init__.py", line 282, in emit
    remove = [l for l in listeners if not l(*args, **kwargs)]
  File "/app/neo-python/venv/lib/python3.6/site-packages/pymitter/__init__.py", line 282, in <listcomp>
    remove = [l for l in listeners if not l(*args, **kwargs)]
  File "/app/neo-python/venv/lib/python3.6/site-packages/pymitter/__init__.py", line 310, in __call__
    self.func(*args, **kwargs)
  File "/app/neo-python/neo/contrib/smartcontract.py", line 71, in call_on_event
    [event_handler(sc_event) for event_handler in handlers]
  File "/app/neo-python/neo/contrib/smartcontract.py", line 71, in <listcomp>
    [event_handler(sc_event) for event_handler in handlers]
  File "neo/contrib/narrative/nrve-niche-payment-handler.py", line 90, in sc_notify
    traceback.print_stack()
Traceback (most recent call last):
  File "neo/contrib/narrative/nrve-niche-payment-handler.py", line 87, in sc_notify
    self.do_sc_notify(event)
  File "neo/contrib/narrative/nrve-niche-payment-handler.py", line 97, in do_sc_notify
    if not len(event.event_payload):
TypeError: object of type 'ContractParameter' has no len()
[I 180719 05:27:02 LevelDBBlockchain:854] Could not persist block object of type 'ContractParameter' has no len() 
Unhandled error in Deferred:

```

**Comment by brianlenz** [comment]
Probably will become an issue for @markremi in https://github.com/NarrativeCompany/narrative-platform/issues/207.

**Comment by brianlenz** [comment]
This is caused by a neo-python change:

https://github.com/CityOfZion/neo-python/commit/cf770422c144d5ada0d4ab195b0a302967fdc6e6#diff-b0c33fb6c0c9db393f2c8faa078b2762R79
